spring.config.import=optional:file:./application-local.properties
server.port=8084

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui-entity.html
springdoc.swagger-ui.operationsSorter=method

vaadin.urlMapping=/app/*
vaadin.pnpm.enable=false